const domSelectors = {
    mgIons: document.querySelector('#main-group-ions'),
    tsIons: document.querySelector('#transition-metal-ions'),
    cationDropdown: document.querySelector('#cation-dropdown'),
    anionDropdown: document.querySelector('#anion-dropdown'),
    cationDisplay: document.querySelector('#cation-display'),
    formulaAnswer: document.querySelector('#formula-answer'),
    anionDisplay: document.querySelector('#anion-display'),
    displayFormulaBtn: document.querySelector('#display-formula-btn'),
    displayFormula: document.querySelector('#display-formula'),
    newCationSymbol: document.querySelector('#new-cation-symbol'),
    newAnionSymbol: document.querySelector('#new-anion-symbol'),
    newRandomIonSymbol: document.querySelector('#new-random-ion-symbol'),
    ionSymbol: document.querySelector('#ion-symbol'),
    nameIonAnswer: document.querySelector('#name-ion-answer'),
    checkIonNameBtn: document.querySelector('#check-ion-name'),
    displayNameIonAnswer: document.querySelector('#display-name-ion-answer'),
    newCationName: document.querySelector('#new-cation-name'),
    newAnionName: document.querySelector('#new-anion-name'),
    newRandomIonName: document.querySelector('#new-random-ion-name'),
    ionName: document.querySelector('#ion-name'),
    checkIonFormulaBtn: document.querySelector('#check-ion-formula'),
    formulaIonAnswer: document.querySelector('#formula-ion-answer'),
    displayFormulaIonAnswer: document.querySelector('#display-formula-ion-answer'),
}

export default domSelectors;